# Generated by Django 4.1 on 2022-08-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='emeail_address',
            new_name='email_address',
        ),
    ]
